name: "application-1"
registryName: "registry-1"
version: "3.0.0"
replicas: 3
artifactId: "application-1"
groupId: "org.qubership"
supportParallelDeploy: true
deployParameters: {}
technicalConfigurationParameters: {}
