name: "application-3"
registryName: "registry-2"
artifactId: "application-3"
groupId: "org.qubership"
supportParallelDeploy: true
deployParameters: {}
technicalConfigurationParameters: {}
metadata:
  helmReleaseNameStrategy: perApplication
